# Generated by Django 2.2.12 on 2020-04-05 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_load_initial_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='footer',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
